-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit.git
    sha: v0.13.6
    hooks:
    -   id: validate_config
